version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: devlog
      MYSQL_USER: testuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - backend-network

  backend:
    container_name: backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/devlog?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - backend-network
    restart: on-failure
    ports:
      - "8080:8080"

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - mysql
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:  # 🔧 추가됨
